services:
  tesla_http_proxy:
    build: .
    ports:
      - "80:80"
    environment:
      - TESLA_HTTP_PROXY_HOST=0.0.0.0
      - TESLA_HTTP_PROXY_PORT=80
      - TESLA_HTTP_PROXY_TIMEOUT=10s
      - TESLA_KEY_FILE=/config/private_key
      - TESLA_VERBOSE=true
    volumes:
      - ./config:/config