name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Azure 로그인
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}

      - name: 컨테이너 앱 시크릿 설정
        run: |
          az containerapp secret set \
            --name drev-tesla-proxy \
            --resource-group testResourceGroup \
            --secrets \
              tesla-key-file="${{ secrets.TESLA_KEY_FILE }}" \
              tesla-http-proxy-tls-cert="${{ secrets.TESLA_HTTP_PROXY_TLS_CERT }}" \
              tesla-http-proxy-tls-key="${{ secrets.TESLA_HTTP_PROXY_TLS_KEY }}"
        shell: bash

      - name: 컨테이너 앱 배포
        run: |
          az containerapp update \
            --resource-group testResourceGroup \
            --name drev-tesla-proxy \
            --yaml container-app.yml
        shell: bash