name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Azure 로그인
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}

      - name: 컨테이너 앱 배포
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: testResourceGroup
          yamlConfigPath: containerapp.yaml
        env:
          TESLA_KEY_FILE: ${{ secrets.TESLA_KEY_FILE }}
          TESLA_HTTP_PROXY_TLS_CERT: ${{ secrets.TESLA_HTTP_PROXY_TLS_CERT }}
          TESLA_HTTP_PROXY_TLS_KEY: ${{ secrets.TESLA_HTTP_PROXY_TLS_KEY }}