name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: 키 파일 생성
        run: |
          mkdir -p ./config
          echo "${{ secrets.TESLA_HTTP_PROXY_TLS_CERT }}" > ./config/cert.pem
          echo "${{ secrets.TESLA_HTTP_PROXY_TLS_KEY }}" > ./config/key.pem
          echo "${{ secrets.TESLA_KEY_FILE }}" > ./config/private_key.pem
          ls -al ./config
        shell: bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}

       - name: Azure Container Apps에 배포
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: drev-tesla-proxy
          resourceGroup: testResourceGroup
          imageToDeploy: tesla/vehicle-command:latest

          # 시크릿 설정
          secrets: |
            TESLA_KEY_FILE=${{ secrets.TESLA_KEY_FILE }}
            TESLA_HTTP_PROXY_TLS_CERT=${{ secrets.TESLA_HTTP_PROXY_TLS_CERT }}
            TESLA_HTTP_PROXY_TLS_KEY=${{ secrets.TESLA_HTTP_PROXY_TLS_KEY }}

          # 볼륨 마운트 설정
          revisionSuffix: unique-suffix
          volumeMounts: |
            /config=secret:TESLA_KEY_FILE:private_key.pem,secret:TESLA_HTTP_PROXY_TLS_CERT:cert.pem,secret:TESLA_HTTP_PROXY_TLS_KEY:key.pem

          # 환경 변수 설정
          environmentVariables: >
            TESLA_HTTP_PROXY_TLS_CERT=/config/cert.pem
            TESLA_HTTP_PROXY_TLS_KEY=/config/key.pem
            TESLA_HTTP_PROXY_HOST=0.0.0.0
            TESLA_HTTP_PROXY_PORT=4443
            TESLA_HTTP_PROXY_TIMEOUT=10s
            TESLA_KEY_FILE=/config/private_key.pem
            TESLA_VERBOSE=true