name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/tesla-vehicle-command-proxy:${{ github.sha }} .

       - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.DEV_ACR_USERNAME }}
          password: ${{ secrets.DEV_ACR_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/tesla-vehicle-command-proxy:${{ github.sha }}

      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          azureCredentials: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP }}
          containerAppName: test-tesla-vehicle-proxy
          imageToDeploy: ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/tesla-vehicle-command-proxy:${{ github.sha }}
          environmentVariables: >
            TESLA_HTTP_PROXY_HOST=0.0.0.0
            TESLA_HTTP_PROXY_PORT=8080
            TESLA_HTTP_PROXY_TIMEOUT=10s
            TESLA_KEY_FILE=/config/tesla-key
            TESLA_VERBOSE=true
          volumes: |
            [
              {
                "name": "secret-volume",
                "storageType": "Secret"
              },
            ]
          volumeMounts: |
            [
              {
                "mountPath": "/config",
                "volumeName": "secret-volume"
              }
            ]