name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: 키 파일 생성
        run: |
          mkdir -p ./config
          echo "${{ secrets.TESLA_HTTP_PROXY_TLS_CERT }}" > ./config/cert.pem
          echo "${{ secrets.TESLA_HTTP_PROXY_TLS_KEY }}" > ./config/key.pem
          echo "${{ secrets.TESLA_KEY_FILE }}" > ./config/private_key.pem
          ls -al ./config
        shell: bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: mytestacr0613.azurecr.io
          registryUsername: ${{ secrets.DEV_ACR_USERNAME }}
          registryPassword: ${{ secrets.DEV_ACR_PASSWORD }}
          containerAppName: drev-tesla-proxy
          resourceGroup: testResourceGroup
          imageToBuild: mytestacr0613.azurecr.io/drev-tesla-proxy:${{ github.sha }}
          environmentVariables: |
            TESLA_HTTP_PROXY_TLS_CERT=/config/cert.pem
            TESLA_HTTP_PROXY_TLS_KEY=/config/key.pem
            TESLA_HTTP_PROXY_HOST=0.0.0.0
            TESLA_HTTP_PROXY_PORT=4443
            TESLA_HTTP_PROXY_TIMEOUT=10s
            TESLA_KEY_FILE=/config/private_key.pem
            TESLA_VERBOSE=true