name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Azure 로그인
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_ACR_AZURE_CREDENTIALS }}
      
      # 3. ACR 로그인
      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # 4. Docker 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/tesla-vehicle-command-proxy:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/tesla-vehicle-command-proxy:latest

      - name: 컨테이너 앱 배포
        run: |
          az containerapp update \
            --resource-group testResourceGroup \
            --name tesla-vehicle-command-proxy \
            --yaml container-app.yml
        shell: bash